require:
  - ts-node/register/transpile-only
  - tsconfig-paths/register
  - chai/register-expect.js
reporter: 'spec'
package: ./package.json
parallel: false
timeout: 5000
ui: bdd
recursive: true
jobs: 10
exclude:
  - node_modules
